### PR TITLE
ADD: tailwind prefix to prevent override

### PR DESCRIPTION
**Pull request by AwolDes**
Without a `prefix` set for tailwind, the configuration for this package would clash with projects importing it.  The prefix chosen is `ws-` standing for "wallet selector"

@mitchbne thank you for reporting this bug.

### CODE REVIEW

**Review by mitchbne — COMMENTED** [review]
How come the `yarn.lock` is changing so drastically?

**Comment by AwolDes** [comment]
@mitchbne it looks like in this case, the existing `yarn.lock` was generated with yarn `v1`, and I have `v3` locally.

**Review by mitchbne — APPROVED** [review]
No worries, ship 🚀

**Comment by AwolDes** [comment]
image

Published

**Pull request merged**
